{% set version = "9.0.0.21" %}
{% set onload_version = "9.0.0" %}

package:
  name: tcpdirect
  version: {{ version }}

source:
  - url: https://github.com/Xilinx-CNS/tcpdirect/archive/refs/tags/tcpdirect-{{ version }}.tar.gz
    sha256: 8911c4299e3a791087a55702af9362b252bf068b7921ac8c463b999ac3392fdc
    folder: tcpdirect
    patches:
      - install.diff

  - url: https://github.com/Xilinx-CNS/onload/archive/refs/tags/v{{ onload_version }}.tar.gz
    sha256: 926b62582df5eb4b38165725e836160fbfe62efa3c055a0e5be0c3e9486717dc
    folder: onload

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/zf/zf_tcp.h
    - test -f $PREFIX/bin/zf_stackdump

about:
  home: https://www.xilinx.com/support/download/nic-software-and-drivers.html#tcpdirect
  summary: 'AMD TCPDirect ultra low latency kernel bypass TCP and UDP implementation for AMD Solarflare network adapters, to be used with corresponding versions of Onload'
  license: MIT AND BSD-3-Clause AND LGPL-3.0-only
  license_file: tcpdirect/doc/LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
